[[constraint]]
  branch = "master"
  name = "github.com/aws-samples/lambda-go-samples"

[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.1.0"

[[constraint]]
  name = "github.com/nlopes/slack"
  version = "0.2.0"
